clone:
  path: github.com/udistrital/titan_cliente

build:

  # build and test the go program
  go:
    image: node:1.5.0
    commands:
     - apt-get install -y zip
     - npm install -g grunt-cli bower
     - echo '{ "allow_root": true }' > /root/.bowerrc
     - npm install
     - bower install
     - grunt build
     - zip -r dist.zip dist/

    when:
      branch: develop
      event: push

  # prepare imagedef.json and app.zip for deployment
  # sed:
  #   image: alpine
  #   commands:
  #     - sed -i 's|SED_TAG|'${CI_COMMIT:0:7}'|' imagedef.json
  #     - apk -U add zip
  #     - zip app.zip imagedef.json
  #   when:
  #     branch: develop
  #     event: push

publish:

  # build and push docker image to docker hub
  # docker:
  #   repo: oas0/titan_cliente
  #   tag:
  #     - $${COMMIT:0:7}
  #     - latest
  #   username: $$DRONE_DOCKERID_LOGIN
  #   password: $$DRONE_DOCKERID_PASSWORD
  #   email: computoud@googlegroups.com
  #   when:
  #     branch: develop
  #     event: push

  # upload app.zip to s3 bucket for CodePipline
  s3:
    region: "us-east-1"
    bucket: "drone-helper-bucket"
    access_key: $$DRONE_AWS_ACCESS_KEY_ID
    secret_key: $$DRONE_AWS_SECRET_ACCESS_KEY
    source: app.zip
    target: /apps/titan_cliente-$$BRANCH.zip
    when:
      branch: develop
      event: push

notify:

  # notify telegram
  webhook:
    urls:
      - https://api.telegram.org/bot$$DRONE_TELEGRAM_TOKEN/sendMessage
    content_type: application/json
    template: >
      {
        "chat_id": "-129350403",
        "parse_mode": "Markdown",
        "text": "`{{repo.full_name}}` [{{uppercase build.status}}]({{build.link_url}}) `{{build.branch}}`@{{truncate build.commit 7}}"
      }
    when:
      branch: develop
      event: push
